server:
  port: 8080
  servlet:
    contextPath: /controle-de-ponto
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/controle-de-ponto?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect