ALTER TABLE momento CHANGE `id` `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE registro_de_trabalho CHANGE `id` `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE alocacao CHANGE `id` `id` BIGINT NOT NULL AUTO_INCREMENT;